version: '3.8'

services:
  php:
    image: php:8.2-apache
    container_name: php-app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    environment:
      - TZ=Europe/Moscow
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: atm_app
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 1234
    ports:
      - "3305:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mysql-data:
